services:
  - type: web
    name: oftalmetryc_sistema
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python boot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromSecret: DATABASE_URL